// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '515867287206',
    projectId: 'thomas-munz',
    authDomain: 'thomas-munz.firebaseapp.com',
    databaseURL: 'https://thomas-munz-default-rtdb.firebaseio.com',
    storageBucket: 'thomas-munz.appspot.com',
    measurementId: 'G-PS1B7ZF8LR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '515867287206',
    projectId: 'thomas-munz',
    databaseURL: 'https://thomas-munz-default-rtdb.firebaseio.com',
    storageBucket: 'thomas-munz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '515867287206',
    projectId: 'thomas-munz',
    databaseURL: 'https://thomas-munz-default-rtdb.firebaseio.com',
    storageBucket: 'thomas-munz.appspot.com',
    iosClientId:
        '515867287206-lfofloo8b171lhddh52err76jd5ooio9.apps.googleusercontent.com',
    iosBundleId: 'ru.thomasmuenz.ios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '515867287206',
    projectId: 'thomas-munz',
    databaseURL: 'https://thomas-munz-default-rtdb.firebaseio.com',
    storageBucket: 'thomas-munz.appspot.com',
    iosClientId:
        '515867287206-kiaueskema6bl5rtdnjlkq0fcdcebblk.apps.googleusercontent.com',
    iosBundleId: 'com.thomasmunz.thomasMunzClient',
  );
}
